# Tensorflow Recommendation System

In [1]:
from modules.data_loader import load_data
from modules.preprocess_data import preprocess
from config.config import Config

2024-11-07 09:33:55.287106: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-07 09:33:55.359172: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1730968435.400287   25306 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730968435.413850   25306 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-07 09:33:55.482508: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [ ]:
train_df, test_df, article_df = load_data()
preprocessed_hm_data = preprocess(train_df, test_df, article_df, batch_size=Config.batch_size)

Data was already pickeled!


I0000 00:00:1730968441.729706   25306 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5564 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6


In [ ]:
preprocessed_hm_data.all_articles

<_UnbatchDataset element_spec={'article_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'product_type_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'product_group_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'colour_group_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'department_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'index_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'section_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'garment_group_name': TensorSpec(shape=(), dtype=tf.int64, name=None)}>

In [ ]:
candidate_data = preprocessed_hm_data.all_articles.batch(128)
for example in candidate_data.take(1):
    print(example)

{'article_id': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'product_type_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'product_group_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'colour_group_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'department_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'index_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'section_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'garment_group_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>}
{'article_id': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'product_type_name': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'product_group_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'colour_group_name': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'department_name': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'index_name': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'section_name': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'garment_group_name': <tf.Tensor: shape=(), dty

2024-11-07 09:30:06.571750: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


: 