# Tensorflow Recommendation System

In [1]:
from modules.data_loader import load_data
from modules.preprocess_data import preprocess
from config.config import Config

2024-11-07 10:04:37.307406: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-07 10:04:37.469844: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1730970277.530333   37761 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730970277.547586   37761 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-07 10:04:37.699124: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [2]:
train_df, test_df, article_df = load_data()
preprocessed_hm_data = preprocess(train_df, test_df, article_df, batch_size=Config.batch_size)

Data was already pickeled!


I0000 00:00:1730970284.064531   37761 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5564 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6


Done preparing the lookups...
Done generating the training set...
Done generating the test set...
Done generating the article data...


In [3]:
preprocessed_hm_data.all_articles

<_UnbatchDataset element_spec={'article_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'product_type_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'product_group_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'colour_group_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'department_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'index_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'section_name': TensorSpec(shape=(), dtype=tf.int64, name=None), 'garment_group_name': TensorSpec(shape=(), dtype=tf.int64, name=None)}>

In [6]:
for i in preprocessed_hm_data.train_ds.take(2):
    print(i)

{'article_id': <tf.Tensor: shape=(512,), dtype=int64, numpy=
array([ 389,  312,  523,  105,  701,  401,  274,  325,  187,  131,  568,
         85,  535,   92,  714,  391,  837,  248,  329,   84,    2,  766,
        177,  144,  768,  635,  735,   60,  168,  572,  528,  541,  413,
        302,   33,  744,  188,  597,  658,  167,  314,   54,  302,  750,
          3,  222,  573,  147,  127,  645,   16,  336,  620,  343,   70,
         19,  799,  817,  260,  850,  755,  239,  673,  610,  116,  239,
        400,  885,  852,  753,  352,  612,  340,   18,  274,  302,  666,
        872,  844,  699,  806,  608,  698,  244,  517,   35,  822,  445,
        621,  437,  406,  838,  351,   69,  236,  816,  711,  735,  772,
        239,  578,   51,  875,  396,  309,  832,  231,  873,  182,  334,
        749,  452,   96,  129,  582,  282,   51,  220,  615,  372,  659,
        549,  192,  824,   11,  524,  731,  748,  779,  796,  305,   60,
        514,  161,  159,  161,  295,  327,  210,  869,  736,  5

2024-11-07 10:05:21.075277: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [ ]:
candidate_data = preprocessed_hm_data.all_articles.batch(128)
for example in candidate_data.take(1):
    print(example)

{'article_id': <tf.Tensor: shape=(128,), dtype=int64, numpy=
array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128])>, 'product_type_name': <tf.Tensor: shape=(128,), dtype=int64, numpy=
array([ 1,  2,  2,  2,  3,  2,  2,  2,  2,  4,  2,  4,  5,  6,  7,  8,  9,
       10,  2, 11, 10, 12, 10, 11, 13, 14, 14,  6,  3, 12, 14, 12, 14, 15,
       16

: 